### ISSUE TITLE
hardware/cpu/intel add embedded cpus

### ISSUE THREAD

**Issue by apdibbo** [quattor/template-library-standard#103]
Would it be possible to also add embedded type cpus to this template library such as the Atom c2558 and the Celeron 1047UE?

This is because these CPUs are used in the Mellanox SN2100 and SN2700 switches respectively and we would like to be able to manage these with Quattor.

**Comment by jrha** [comment]
Yes, but...

**Comment by jrha** [comment]
I've imported the CPUs you requested, importing more from ARK would require some sane way of identifying "useful" CPUs (the embedded market segment is rather large.
