### ISSUE TITLE
cvmfs client is not configured correctly

### ISSUE THREAD

**Issue by Pansanel** [quattor/template-library-standard#107]
Last updates in the cvmfs client configuration has added a space after the semi-colon in the definition of the CVMFS_SERVER_URL variable.
For example, in our log we can see:
(download) escaped
http://cernvmfs.gridpp.rl.ac.uk:8000/opt/cms/.cvmfspublished to
%20http://cernvmfs.gridpp.rl.ac.uk:8000/opt/cms/.cvmfspublished
[01-23-2018 16:44:16 CET]
A '%20' string has been added to the url and cvmfs is failing.

**Comment by jrha** [comment]
Thanks for catching this, it was my fault :man_facepalming:
