### ISSUE TITLE
frontier file name 'customized.sh'

### ISSUE THREAD

**Issue by almumontiel** [quattor/template-library-standard#128]
The configuration of a frontier-squid instance creates "customized.sh" (ending with d), instead of the one expected by frontier-squid, which is "customize.sh"

In line 29 of  template-library-standard/features/frontier/config.pan 
'/software/components/filecopy/services/{/etc/squid/customized.sh}' = dict(

Is there any reason for this?
The command  'service frontier-squid reload' does not include the configuration from the file "customized.sh" file

**Comment by jrha** [comment]
I don't think so, looks like a typo to me.
