### ISSUE TITLE
EL8: NetworkManager rebuild resolv.conf at each reboot

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-standard#153]
In recent updates of EL8 (CentOS Stream), NetworkManager rebuild `resolv.conf` at each reboot with an inappropriate content, breaking name resolution (and thus ability to fix the problem with Quattor). It doesn't happen on all machines, what triggers it is not clear but it is expected that by default NetworkManager may take control of `resolv.conf`. `dns=none` should be set by Quattor in the configuration file to prevent this to happen, as it manages the `resolv.conf` content.

Several articles can be found about this, most of them on Ubuntu but it is the same NetworkManager...

**Comment by jrha** [comment]
Fixed in the `nmstate` backend, so a stand-alone fix is no longer required.
