### ISSUE TITLE
frontier feature outdated?

### ISSUE THREAD

**Issue by pigay** [quattor/template-library-standard#47]
I'm looking for a component to build a Squid proxy (for CVMFS).

I gave a look at frontier feature, but it seems to be a bit outdated:
* uses PKG_ARCH_GLITE while not in the template-library-grid
* uses explicit frontier-squid rpm version number (not yum based spma)

These are easy to fix, but is this feature still maintained? Would we better use something else?

Thanks n advance,

Pierre

**Comment by jrha** [comment]
@guillaume-philippon, @Pansanel any idea?

**Comment by Pansanel** [comment]
I did not work on this component. It may be outdated. @guillaume-philippon?

**Comment by pigay** [comment]
As far as I've seen, this component was not used by many people. I finally managed to configure a normal squid proxy with ncm-filecopy.

Maybe this one could be removed from the repo since it is broken?

**Comment by jrha** [comment]
Seems like we should remove it, although metaconfig would probably be a better choice than filecopy!

**Comment by pigay** [comment]
You're right. Metaconfig would be better, but I couldn't decide what format module to use to generate squid configuration file, so filecopy was the easy way for me ;)

Thanks anyway,

Pierre
