### ISSUE TITLE
Move hardware/nic/legacy contents to appropriate hardware/nic/vendor

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-standard#77]
As discussed in [#69](https://github.com/quattor/template-library-standard/pull/69#issuecomment-242094658), templates originally in `hardware/nic` and moved to `hardware/nic/legacy` during #69 should have been moved to the appropriate `hardware/nic/vendor` namespace. The vendor for these templates is mentioned in the `name` attribute so it should be pretty straightforward to do...

**Comment by jrha** [comment]
I don't think this is the right thing to do, I think they should simply be deleted in a later release.
They should have been superseded by the new templates @brunocanning produced.

**Comment by jouvin** [comment]
I missed that the new templates were basically matching the old ones... My concern, based on my previous experience with `legacy` things, is that this is always hard to decide to delete it... And I don't see the real added value of creating this `nic/legacy` rather than just adding the deprecation to the original template under `nic`. At the end this is just adding to the mess, creating new templates that may appear legitimate to use. My preference would have been one of the following approaches:
- Keep the original template at the original place and add the deprecation warning: this will make removal easier
- Just remove the original templates from the release: sites could always keep the previous ones. But this is probably not the right approach on the long run, as there will be no deprecation warning to push the site to migrate.

Looking at the contents of `nic/legacy` I don't have the feeling that it will be that easy to find the replacement in the vendor-based templates. May be a small table somewhere on our web site with the usual "mapping" may help... I don't know if it makes sense...

**Comment by jrha** [comment]
An alternative would be to rename `legacy` to `by_driver` or something similar.

**Comment by jrha** [comment]
I should also add that the time for review is before PRs are merged, not after.
#69 was open for almost four months which should have been plenty of time.

**Comment by jouvin** [comment]
@jrha I completely agree and I should apologize for overlooking this problem the first time I looked at the PR.... And I was away when the last comments before the merge were done. Anyway the PR does nothing wrong and my suggestion is just a proprosed enhancement!

**Comment by jouvin** [comment]
BTW, suggestion to use `by_driver` rather than `legacy` (https://github.com/quattor/template-library-standard/issues/77#issuecomment-242344713) is fine with me and may be better reflects that these new templates (under `by_driver`) are legitimate to use. Just the ones under `nic/` are deprecated.

**Comment by brunocanning** [comment]
Whilst most of the legacy templates are named by driver, some are actually named by model, e.g. mcp55 and bcm5700, both of which have new, expanded templates under `hardware/nic/nvidia/` and `hardware/nic/broadcom/`, respecively. In these two cases, the original template was detailed enough and I had access to a host fitted with these nics in order to construct new templates. For these reasons, I thought that moving all the old templates to `hardware/nic/legacy` was easier and cleaner. HTH.

**Comment by jouvin** [comment]
@brunocanning to be clear, I think you did a great job! My point is just to enhance it a little bit as I have the concerns expressed above with anything named `legacy` but intended to last quite some time... `by_driver` seems to me a little bit better. I'd say that if an old templatehas a matching by-vendor one, even if it is not exactly the same (for example the `name` attribute is not worded the same way), the deprecated template should include this one and none should be created in `by_driver`.
