### ISSUE TITLE
nic/by_driver/bnx2* templates: improperly designated as Qlogic drivers

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-standard#82]
I saw that in the new `nic/by_driver/bnx2*`templates, the name starts with `QLogic...`. For me (I think I am the original author of the template), `bnx` was standing for `Broadcam NetExtreme`, thus the original description in the `name` attribute. It is very minor but does anybody has a strong idea on this point?

**Comment by jrha** [comment]
http://www.qlogic.com/solutions/Pages/Ethernet-NIC-FAQs.aspx

**Comment by jrha** [comment]
Qlogic acquired the rights to NetExtreme, so it could legitimately be either, but as stated, I took the value of `MODULE_DESCRIPTION` from the kernel as the preferred value. See https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/net/ethernet/broadcom/bnx2.c?id=refs/tags/v4.8-rc6#n78

**Comment by jouvin** [comment]
But https://www.broadcom.com/press/release.php?id=s826425 explains that QLogic bought NetXtreme II from Broadcoam... So probably both are correct!

**Comment by jrha** [comment]
I think the key thing is that the _cards_ are likely to me Broadcom but the _driver_ is QLogic.
